name: 'Install tkn'
description: 'Install Tekton CLI'
branding:
  icon: 'terminal'
  color: 'purple'
inputs:
  version:
    description: 'Version of tkn to install (latest, v0.18.0, etc.)'
    required: false
    default: 'latest-release'  
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set -ex

      # Install tkn:
      # - if version is "latest-release", look up latest release.
      # - otherwise, install the specified version.
      case ${{ inputs.version }} in
      latest-release)
        tag=$(curl -L -s -u "username:${{ github.token }}" https://api.github.com/repos/tektoncd/cli/releases/latest | jq -r '.tag_name')
        ;;
      *)
        tag="${{ inputs.version }}"
      esac
      
      # Get the operating system
      os=${{ runner.os }}
      if [[ $os == "macOS" ]]; then
        os="Darwin"
      fi
      
      echo "Installing tkn@${tag} for ${os}"
      
      # Get the tar.xz
      curl -fsL https://github.com/tektoncd/cli/releases/download/${tag}/tkn_${tag:1}_${os}_x86_64.tar.gz | sudo tar xzf - -C /usr/local/bin tkn
      