name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: tkn version